# nutzt die offizielle nginx als basis
FROM nginx

# copiert helloworld.html ins standardspeicherort fuer html-dateien in nginx
COPY helloworld.html /usr/share/nginx/html/

# ermoeglicht das abhoeren der requests durch port 80
EXPOSE 80
