version: '3.8'

volumes:
  rheinmetall:
  tmpfs:

services:
  kn05c1:
    image: nginx:latest
    volumes:
      - type: volume
        source: rheinmetall
        target: /volume
      - type: bind
        source: /c/kn05
        target: /bind
      - type: tmpfs
        target: /tmpfs

  kn05c2:
    image: nginx:latest
    volumes:
      - rheinmetall:/volume
